version: '3.7'
services:
  api:
    build:
      context: '.'
      target: 'build'
      args:
        buildcmd: 'npm run build'
    command: 'npm run start:debug'
    container_name: '${APP_NAME}'
    image: '${APP_NAME}:latest'
    init: true
    ports:
      - '${LOCAL_APP_PORT}:3000'
      - '${LOCAL_APP_PORT_DEBUG}:9229'
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'